version: '3'
volumes:
  pentaho_data:
services:
  pen-server:
    build: .
    image: lpaschoal/pentaho_server:9.4
    container_name: pentaho-server
    networks:
      - rede_pentaho
    restart: always
    volumes:
      - pentaho_data:/opt/pentaho/pentaho-server
    ports:
      - "8080:8080"
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1 #windows only
      - TZ=America/Sao_Paulo
networks:
  rede_pentaho:
      name: network_pentaho
